/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.pss.view;

import com.pss.po.support.LoginUser;
import com.pss.util.FrameUtil;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 * 进销存系统主窗体(管理员)
 * @author 曲健磊
 */
public class AdminMainFrame extends javax.swing.JFrame {
    // 1.添加JDesktopPane
    JDesktopPane desk = new JDesktopPane();
    /**
     * Creates new form PssMainFrame
     */
    public AdminMainFrame() {
        initComponents();
        // 2.主窗体设置桌面面板
        this.setContentPane(desk);
        String userName = LoginUser.user.getUserName();
        JOptionPane.showMessageDialog(null, "欢迎您：" + userName + "！");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("进销存管理系统");
        setBackground(new java.awt.Color(0, 51, 153));

        jMenu1.setText("基本资料管理");
        jMenu1.setToolTipText("进销存管理");

        jMenuItem1.setText("商品管理");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("供应商管理");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("客户管理");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("员工管理");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("采购管理");

        jMenuItem5.setText("采购查询");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("采购入库");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("销售管理");

        jMenuItem8.setText("销售查询");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("销售出库");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("统计查询");

        jMenuItem13.setText("采购统计");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuItem14.setText("库存查询");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 显示内部窗体的公共方法
     * @param frame 
     */
    public void showFrame(JInternalFrame frame){
        this.desk.remove(frame);
        //将内部窗体添加到桌面面板
        this.desk.add(frame);
        //显示
        frame.setVisible(true);
        frame.toFront();
        try {
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(AdminMainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * 弹出商品管理对话框
     * @param evt 
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // 创建JInternalFrame对象
        ProductFrame pframe = (ProductFrame) FrameUtil.buildFrame(ProductFrame.class);
        // 显示
        showFrame(pframe);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * 弹出供应商管理对话框
     * @param evt 
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // 创建JInternalFrame对象
        SupplierFrame sframe = (SupplierFrame) FrameUtil.buildFrame(SupplierFrame.class);
        // 显示
        showFrame(sframe);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * 弹出客户管理对话框
     * @param evt 
     */
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // 创建JInternalFrame对象
        CustomerFrame cframe = (CustomerFrame) FrameUtil.buildFrame(CustomerFrame.class);
        // 显示
        showFrame(cframe);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * 弹出员工管理对话框
     * @param evt 
     */
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // 创建JInternalFrame对象
        UserFrame uframe = (UserFrame) FrameUtil.buildFrame(UserFrame.class);
        // 显示
        showFrame(uframe);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * 弹出采购查询对话框
     * @param evt 
     */
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // 创建JInternalFrame对象
        PurchaseQueryFrame pframe = (PurchaseQueryFrame) FrameUtil.buildFrame(PurchaseQueryFrame.class);
        // 显示
        showFrame(pframe);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * 弹出采购入库对话框
     * @param evt 
     */
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // 创建JInternalFrame对象
        PurchaseInFrame pframe = (PurchaseInFrame) FrameUtil.buildFrame(PurchaseInFrame.class);
        // 显示
        showFrame(pframe);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * 弹出销售查询对话框
     * @param evt 
     */
    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // 创建JInternalFrame对象
        SalesQueryFrame sframe = (SalesQueryFrame) FrameUtil.buildFrame(SalesQueryFrame.class);
        // 显示
        showFrame(sframe);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * 弹出销售出库对话框
     * @param evt 
     */
    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // 创建JInternalFrame对象
        SalesOutFrame sframe = (SalesOutFrame) FrameUtil.buildFrame(SalesOutFrame.class);
        // 显示
        showFrame(sframe);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * 弹出采购统计对话框
     * @param evt 
     */
    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // 创建JInternalFrame对象
        PurchaseCountFrame pframe = (PurchaseCountFrame) FrameUtil.buildFrame(PurchaseCountFrame.class);
        // 显示
        showFrame(pframe);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    /**
     * 弹出库存查询对话框
     * @param evt 
     */
    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // 创建JInternalFrame对象
        InventoryQueryFrame iframe = (InventoryQueryFrame) FrameUtil.buildFrame(InventoryQueryFrame.class);
        // 显示
        showFrame(iframe);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
